sudo: required
language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn global add @angular/cli
script:
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN