sudo: required
language: node_js
node_js:
  - "12"
cache:
  yarn: true
script:
  - yarn global add @angular/cli
deploy:
  - provider: firebase
    script: ng build --configuration=staging
    project: staging
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: dev
  - provider: firebase
    script: ng build --configuration=production
    project: production
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master