sudo: required
language: node_js
node_js:
  - "12"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: deploy to staging
      script:
        - yarn global add @angular/cli
        - ng build --configuration=staging
      deploy:
        skip_cleanup: true
        provider: firebase
        project: staging
        token:
          secure: $FIREBASE_TOKEN
    - stage: deploy to production
      script:
        - yarn global add @angular/cli
        - ng build --configuration=production
      deploy:
        skip_cleanup: true
        provider: firebase
        project: production
        token:
          secure: $FIREBASE_TOKEN
stages:
  - name: deploy to staging
    if: branch = staging
  - name: deploy to production
    if: branch = master