sudo: required
language: node_js
node_js:
  - "12"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @angular/cli]
deploy:
  - provider: firebase
    script: ng build --configuration=staging
    project: staging
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: dev
  - provider: firebase
    script: ng build --configuration=production
    project: production
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master